sudo: false
language: java
jdk:
  - oraclejdk9
before_install:
  - rm "${JAVA_HOME}/lib/security/cacerts"
  - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
cache:
  directories:
    - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_KEY
  file_glob: true
  file: nifi-prometheus-nar/target/*.nar
  skip_cleanup: true
  on:
    tags: true
